apiVersion: v1
kind: Service
metadata:
  labels:
    app: orders-api
  name: orders-api
spec:
  type: NodePort
  ports:
    - name: "orders-api"
      port: 8888
      targetPort: 8888
      nodePort: 31000
  selector:
    app: orders-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders-api
  name: orders-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      annotations:
        dapr.io/app-id: orders-api
        dapr.io/app-port: "8888"
        dapr.io/enabled: "true"
        dapr.io/config: "tracing"
      labels:
        app: orders-api
    spec:
      containers:
        - image: localhost:5001/dapr/orders-api
          name: orders-api
          imagePullPolicy: Always
          env:
            - name: QUARKUS_HTTP_PORT
              value: "8888"
          ports:
            - containerPort: 8888
              name: orders-api