apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value:  amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672
    - name: user
      value: guest
    - name: password
      value: guest